# Generated by Django 3.2 on 2023-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
