# Generated by Django 3.2 on 2023-06-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0002_auto_20230605_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
