# Generated by Django 3.2 on 2023-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0003_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blockquote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
