# Generated by Django 3.2 on 2023-06-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0004_post_blockquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blockquote',
        ),
    ]
