# Generated by Django 3.2 on 2023-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0005_remove_post_blockquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
