# Generated by Django 3.2 on 2023-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0006_alter_post_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blockquote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
