# Generated by Django 3.2 on 2023-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0007_post_blockquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
