# Generated by Django 3.2 on 2023-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0008_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
