# Generated by Django 3.2 on 2023-06-07 01:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0009_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
