# Generated by Django 3.2 on 2023-06-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bola', '0011_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='content',
        ),
    ]
